version: '3'

services:
  mongodb:
    container_name: alpha-centauri-mongodb
    image: mongo:7
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  api:
    container_name: alpha-centauri
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - MONGO_URL=mongodb://alpha-centauri-mongodb:27017/alpha-centauri
      - PORT=5000
    volumes:
      - ./dist:/usr/src/alpha-centauri/dist/
      - ./package.json:/usr/src/alpha-centauri/package.json
    ports:
      - 5000:5000
      - 9222:9222
    links:
      - mongodb
